### ISSUE TITLE
Ruby Errors

### ISSUE THREAD

**Issue by QU35T-code** [ShutdownRepo/Exegol#110]
I have a problem when launching ruby programs (msfconsole, evil-winrm) in exegol :

```bash
root@lab:/workspace# evil-winrm 
Traceback (most recent call last):
        2: from /usr/local/bin/evil-winrm:23:in `<main>'
        1: from /usr/lib/ruby/vendor_ruby/rubygems.rb:300:in `activate_bin_path'
/usr/lib/ruby/vendor_ruby/rubygems.rb:281:in `find_spec_for_exe': can't find gem evil-winrm (>= 0.a) with executable evil-winrm (Gem::GemNotFoundException)
root@lab:/workspace# msfconsole
/usr/bin/msfconsole: 107: exec: /opt/metasploit-framework/bin/../embedded/bin/ruby: Exec format error
```

To fix the problem of evil-winrm for example, I have to download the gem via: `gem install evil-winrm`

exegol is launched from a Mac M2 via the following docker command :

```bash
docker run --interactive --tty --detach --hostname lab -p 9000-9500:9000-9500 -w /workspace --name exegol nwodtuhs/exegol:full
```

Any solutions to solve the ruby problem ?

**Comment by QU35T-code** [comment]
Is the problem related to the fact that I'm on a ARM ?
