### ISSUE TITLE
Windows implementation

### ISSUE THREAD

**Issue by jdouliez** [ShutdownRepo/Exegol#46]
Hi,

**Is Exegol implemented to run on Windows ?**

Based on Docker and python3, Exegol seems to be OK to run on Windows.
But the installation failed here

```
[*] Creating the container
[!] (cmd stderr)     Error response from daemon: failed to mount local volume: mount D:\VM\Exegol/shared-re
sources:/var/lib/docker/volumes/ea114eb184c97f20dc87511f2618285366861236866654bf0f23a5a964e1698e/_data, flags:
0x1000: no such file or directory
[!] Something went wrong...
```

It looks like path is linux/windows mixed.
I don't like Windows but I have to use it, so a linux-based container is a good workaround for me.

Thanks,
JD

**Comment by ShutdownRepo** [comment]
Hmm, it's supposed to work on Windows, but yeah, maybe there's something wrong. I always run exegol from UNIX based systems. Can you make sure the folder "shared-resources" exists in Exegol's install path?
If I remember well, the `D:\VM\Exegol/shared-resources` should work on Windows based systems.
Can you try to provide more information on your setup, maybe run Exegol with `-vv` ?
It's hard for me to find what's preventing Exegol from working in your case

**Comment by jdouliez** [comment]
Yes, I totally understand that.
I did not use Windows OS since 12 years. It's a little bit hard to come back to it.

Here is the runnning command with verbose argument.

````powershell
PS D:\VM\Exegol> python .\exegol.py start -t test -vv
[DEBUG] Local git branch: master
[+] 1 Exegol images exist
[DEBUG] Containers with name exegol-test: 0
[-] Container does not exist
[*] Available images
[DEBUG] Fetching remote image tags, digests and sizes
[DEBUG] └── stable → sha256:aca63b5f95d3c8d797d733f08...
[DEBUG] └── dev → sha256:8adb04fc6e5bef8c5ff3a08da...
[DEBUG] └── ad → sha256:c3a4c783fe3ad5fadd9c50eb7...
[DEBUG] └── light → sha256:92d6779c9943c06e876013549...
[DEBUG] └── osint → sha256:b5478093f6c839b30abaa6841...
[DEBUG] └── web → sha256:fb0ead8023448d38d6e5c3192...
[DEBUG] Fetching local image tags, digests (and other attributes)
[DEBUG] └── stable → sha256:0e054259ecd8eaa8959b0ae93...
┌──────────────┬───────────┬───────────┬───────────────────────────────┐
│ Id           │ Image tag │ Real size │ Type                          │
├──────────────┼───────────┼───────────┼───────────────────────────────┤
│ c3a4c783fe3a │ ad        │ N/A       │ remote (not installed, 3.7GB) │
│ 8adb04fc6e5b │ dev       │ N/A       │ remote (not installed, 7.6GB) │
│ 92d6779c9943 │ light     │ N/A       │ remote (not installed, 2.8GB) │
│ b5478093f6c8 │ osint     │ N/A       │ remote (not installed, 1.9GB) │
│ 5f68363bbf0a │ stable    │ 16.8GB    │ remote (deprecated, 7.6GB)    │
│ fb0ead802344 │ web       │ N/A       │ remote (not installed, 3.6GB) │
└──────────────┴───────────┴───────────┴───────────────────────────────┘

[1;34m[?][0m What image do you want the container to create to be based upon [default: stable]?
[*] Available local containers: 0
┌────┬───────────────┬───────┬────────────────────────┬──────────────────┬────────────────┐
│ Id │ Container tag │ State │ Image (repo/image:tag) │ Creation details │ Binds & mounts │
├────┼───────────────┼───────┼────────────────────────┼──────────────────┼────────────────┤
└────┴───────────────┴───────┴────────────────────────┴──────────────────┴────────────────┘

[DEBUG] Containers with name exegol-stable: 0
[1;34m[?][0m What unique tag do you want to name your container with (one not in list above) [default: stable]? TEST4
[*] Creating the container
[DEBUG] exegol-TEST4 container based on the nwodtuhs/exegol:stable image
[VERBOSE] Enabling display sharing
[VERBOSE] Enabling host networking
[VERBOSE] Sharing /opt/resources (container) ↔ D:\VM\Exegol/shared-resources (host)
[DEBUG] Running command on host with subprocess.Popen(): ['docker', 'create', '--interactive', '--tty', '--volume', 'D:\\VM\\Exegol/shared-data-volumes/TEST4:/data', '--name', 'exegol-TEST4', '--hostname', 'exegol-TEST4', '--env',
'DISPLAY=unixNone', '--volume', '/tmp/.X11-unix:/tmp/.X11-unix', '--env="QT_X11_NO_MITSHM=1"', '--network', 'host', '--mount',
'type=volume,dst=/opt/resources,volume-driver=local,volume-opt=type=none,volume-opt=o=bind,volume-opt=device=D:\\VM\\Exegol/shared-resources', 'nwodtuhs/exegol:stable']
[!] (cmd stderr)     Error response from daemon: failed to mount local volume: mount D:\VM\Exegol/shared-resources:/var/lib/docker/volumes/ba126bb564537645273ab843ddd225d287ba6746adf2b11cd595b53dff2149ad/_data, flags: 0x1000:
no such file or directory
[DEBUG] Containers with name exegol-TEST4: 0
[DEBUG] Loop prevention triggered
[!] Something went wrong...
````

I'll keep digging a little big. Then use a Unix VM :P

**Comment by ShutdownRepo** [comment]
Okay thank you for the follow-up.
Can you try to update your code (`git pull origin master`) and start exegol with the following command instead? `exegol start -vv --no-default --X11 --host-network --shell zsh --container-tag TEST5`.
The step that is erroring is the one binding a host folder to the container's `/opt/resources` one, which is optional really. I think it will work and will allow you to run exegol while we find a fix

**Comment by jdouliez** [comment]
Here are some news...

I've run the commands and then I got : 

````powershell
python exegol.py start -vv --no-default --host-network --shell zsh --container-tag TEST6
[DEBUG] Local git branch: master
[+] 1 Exegol images exist
[DEBUG] Containers with name exegol-TEST6: 0
[-] Container does not exist
[*] Available images
[DEBUG] Fetching remote image tags, digests and sizes
[DEBUG] └── stable → sha256:aca63b5f95d3c8d797d733f08...
[DEBUG] └── dev → sha256:8adb04fc6e5bef8c5ff3a08da...
[DEBUG] └── ad → sha256:c3a4c783fe3ad5fadd9c50eb7...
[DEBUG] └── light → sha256:92d6779c9943c06e876013549...
[DEBUG] └── osint → sha256:b5478093f6c839b30abaa6841...
[DEBUG] └── web → sha256:fb0ead8023448d38d6e5c3192...
[DEBUG] Fetching local image tags, digests (and other attributes)
[DEBUG] └── stable → sha256:0e054259ecd8eaa8959b0ae93...
┌──────────────┬───────────┬───────────┬───────────────────────────────┐
│ Id           │ Image tag │ Real size │ Type                          │
├──────────────┼───────────┼───────────┼───────────────────────────────┤
│ c3a4c783fe3a │ ad        │ N/A       │ remote (not installed, 3.7GB) │
│ 8adb04fc6e5b │ dev       │ N/A       │ remote (not installed, 7.6GB) │
│ 92d6779c9943 │ light     │ N/A       │ remote (not installed, 2.8GB) │
│ b5478093f6c8 │ osint     │ N/A       │ remote (not installed, 1.9GB) │
│ 5f68363bbf0a │ stable    │ 16.8GB    │ remote (deprecated, 7.6GB)    │
│ fb0ead802344 │ web       │ N/A       │ remote (not installed, 3.6GB) │
└──────────────┴───────────┴───────────┴───────────────────────────────┘

[1;34m[?][0m What image do you want the container to create to be based upon [default: stable]?
[*] Available local containers: 1
[DEBUG] Fetching details on containers creation
[DEBUG] Looking for the 'DISPLAY' environment variable in the container /exegol-TEST5
[DEBUG] Looking for the 'host' value in the 'Networks' attribute in the container /exegol-TEST5
[DEBUG] Looking for the 'Devices' attribute in the container /exegol-TEST5
[DEBUG] Looking for the 'Privileged' attribute in the container /exegol-TEST5
[DEBUG] Fetching volumes for each container
Traceback (most recent call last):
  File "D:\VM\Exegol\exegol.py", line 973, in <module>
    globals()[options.action]()
  File "D:\VM\Exegol\exegol.py", line 551, in start
    info_containers()
  File "D:\VM\Exegol\exegol.py", line 879, in info_containers
    if container.attrs["HostConfig"]["Mounts"]:
KeyError: 'Mounts'
PS D:\VM\Exegol> python exegol.py start -vv --no-default --X11 --host-network --shell zsh --container-tag TEST5
[DEBUG] Local git branch: master
[+] 1 Exegol images exist
[DEBUG] Containers with name exegol-TEST5: 1
[+] Container exists
[+] Container is up
[DEBUG] Looking for the 'Devices' attribute in the container /exegol-TEST5
[DEBUG] Looking for the 'Privileged' attribute in the container /exegol-TEST5
[DEBUG] Looking for the 'host' value in the 'Networks' attribute in the container /exegol-TEST5
[VERBOSE] Container was created with host networking
[DEBUG] Looking for the 'DISPLAY' environment variable in the container /exegol-TEST5
[VERBOSE] Container was created with display sharing
[DEBUG] Looking for the 'DISPLAY' environment variable in the container /exegol-TEST5
[*] Running xhost command for display sharing
[DEBUG] Running command on host with subprocess.Popen(): ['xhost', '+local:exegol-TEST5']
Traceback (most recent call last):
  File "D:\VM\Exegol\exegol.py", line 973, in <module>
    globals()[options.action]()
  File "D:\VM\Exegol\exegol.py", line 514, in start
    exec_popen(
  File "D:\VM\Exegol\exegol.py", line 383, in exec_popen
    output = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Users\T0251945\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\T0251945\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
````

Huuum..

**Comment by ShutdownRepo** [comment]
Okay, I think there are multiple issues to be fixed.
In the weeks to come I'll install a Windows on a spare computer and try to debug this
In the mean time, you can also add me on Discord (Shutdown#2539) we can call, share screen, and try to find fixes :man_shrugging:

**Comment by jdouliez** [comment]
Thanks! 
See you there..

**Comment by xdjibi** [comment]
I had exactly the same issue. Installing xhost in my WSL2 Ubuntu 20.04 solved partially the problem :
```
xdjibi@ULTRA-XDJIBI:/opt/Exegol$ python3 exegol.py start -vv --no-default --X11 --host-network --shell zsh --container-tag TEST5
[DEBUG] Local git branch: master
[+] 1 Exegol images exist
[DEBUG] Containers with name exegol-TEST5: 1
[+] Container exists
[+] Container is up
[DEBUG] Looking for the 'Devices' attribute in the container /exegol-TEST5
[DEBUG] Looking for the 'Privileged' attribute in the container /exegol-TEST5
[DEBUG] Looking for the 'host' value in the 'Networks' attribute in the container /exegol-TEST5
[VERBOSE] Container was created with host networking
[DEBUG] Looking for the 'DISPLAY' environment variable in the container /exegol-TEST5
[VERBOSE] Container was created with display sharing
[DEBUG] Looking for the 'DISPLAY' environment variable in the container /exegol-TEST5
[*] Running xhost command for display sharing
[DEBUG] Running command on host with subprocess.Popen(): ['xhost', '+local:exegol-TEST5']
[!] (cmd stderr)     xhost:  unable to open display ""
[*] Entering Exegol
[DEBUG] Running on host with os.system(): docker exec -ti exegol-TEST5 zsh
[Oct 30, 2021 - 21:26:32 (UTC)] exegol-TEST5 /data #
```
I guess the error regarding xhost is related to my distro missing X server like any WSL2 ones.

**Comment by y0no** [comment]
For the update I tried to launch Exegol with WSL2 on Windows 11 with Docker for windows. It works like a charm and handle nicely GUI applications like bloodhound.

The only limitation at this moment is : 
- Exegol need to be executed from WSL (ubuntu for example) for the display sharing between Exegol and Windows.
- The resources directory can't be mounted (because docker volumes  are not on the same WSL distro ?)

**Comment by ShutdownRepo** [comment]
Thank you for this update, this is mostly good news
It can also help @Dramelac and I for the refactoring cycle.

**Comment by Dramelac** [comment]
Windows is now officially supported from Exegol 4.0.0!
